<?
  // Set up some convenience variables:
  $id = $this->driver->getUniqueId();
  $source = $this->driver->getSourceIdentifier();
  if (isset($this->list) && is_object($this->list)) {
    $list_id = $this->list->id;
    $user_id = $this->list->user_id;
  } else {
    $list_id = null;
    $user_id = $this->user ? $this->user->id : null;
  }
  // Thumbnail
  $coverDetails = $this->record($this->driver)->getCoverDetails('list-entry', 'medium', $this->recordLink()->getUrl($this->driver));
  $cover = $coverDetails['html'];
  $thumbnail = false;
  $thumbnailAlignment = $this->record($this->driver)->getThumbnailAlignment('list');
?>
<div class="media result<? if($this->driver->supportsAjaxStatus()): ?> ajaxItem<? endif ?>">
  <input type="hidden" value="<?=$this->escapeHtmlAttr($id) ?>" class="hiddenId"/>
  <input type="hidden" value="<?=$this->escapeHtmlAttr($source) ?>" class="hiddenSource"/>
    <? if ($cover): ?>
      <? ob_start(); ?>
        <div class="media-<?=$thumbnailAlignment ?> <?=$this->escapeHtmlAttr($coverDetails['size'])?>">
          <?=$cover ?>
        </div>
        <? $thumbnail = ob_get_contents(); ?>
      <? ob_end_clean(); ?>
    <? endif; ?>
    <? if ($thumbnail && $thumbnailAlignment == 'left'): ?>
      <?=$thumbnail ?>
    <? endif; ?> 
  <div class="media-body">
          <h3 class="media-heading">
          <? $missing = $this->driver instanceof \VuFind\RecordDriver\Missing; ?>
          <? if (!$missing): ?>
            <?=$this->record($this->driver)->getCheckbox()?>
            <a href="<?=$this->recordLink()->getUrl($this->driver)?>" class="getFull" data-view="<?=$this->params->getOptions()->getListViewOption() ?>"><? endif; ?>
            <?=$this->record($this->driver)->getTitleHtml()?>
          <? if (!$missing): ?></a><? endif; ?>
        </h3>

        <small>
          <? if($this->driver->isCollection()): ?>
            <?=implode('<br>', array_map(array($this, 'escapeHtml'), $this->driver->getSummary())); ?>
          <? else: ?>
            <? $summAuthors = $this->driver->getPrimaryAuthors(); if (!empty($summAuthors)): ?>
              <?=$this->transEsc('by')?>
              <? $authorCount = count($summAuthors); foreach ($summAuthors as $i => $summAuthor): ?>
                <a href="<?=$this->record($this->driver)->getLink('author', $summAuthor)?>"><?=$this->escapeHtml($summAuthor)?></a><?=($i + 1 < $authorCount ? ';' : '') ?>
              <? endforeach; ?>
            <? endif; ?>

            <? $journalTitle = $this->driver->getContainerTitle(); $summDate = $this->driver->getPublicationDates(); ?>
            <? if (!empty($journalTitle)): ?>
              <?=!empty($summAuthor) ? '<br/>' : ''?>
              <?=/* TODO: handle highlighting more elegantly here */ $this->transEsc('Published in') . ' <a href="' . $this->record($this->driver)->getLink('journaltitle', str_replace(array('{{{{START_HILITE}}}}', '{{{{END_HILITE}}}}'), '', $journalTitle)) . '">' . $this->highlight($journalTitle) . '</a>';?>
              <?=!empty($summDate) ? ' (' . $this->escapeHtml($summDate[0]) . ')' : ''?>
            <? elseif (!empty($summDate)): ?>
              <span class="text-muted"><?=$this->transEsc('Published') . ': </span>' . $this->escapeHtml($summDate[0])?>
            <? endif; ?>
            <? $summInCollection = $this->driver->getContainingCollections(); if (false && !empty($summInCollection)): ?>
              <? foreach ($summInCollection as $collId => $collText): ?>
                <div>
                  <b><?=$this->transEsc("in_collection_label")?></b>
                  <a class="collectionLinkText" href="<?=$this->url('collection', array('id' => $collId))?>?recordID=<?=urlencode($this->driver->getUniqueID())?>">
                    <?=$this->escapeHtml($collText)?>
                  </a>
                </div>
              <? endforeach; ?>
            <? endif; ?>
          <? endif; ?>
        </small>

        <div class="last">
          <? if(!$this->driver->isCollection()) {
              if ($snippet = $this->driver->getHighlightedSnippet()) {
                if (!empty($snippet['caption'])) {
                  echo '<strong>' . $this->transEsc($snippet['caption']) . ':</strong> ';
                }
                if (!empty($snippet['snippet'])) {
                  echo '<span class="quotestart">&#8220;</span>...' . $this->highlight($snippet['snippet']) . '...<span class="quoteend">&#8221;</span><br/>';
                }
              }
            } ?>

          <? $listTags = ($this->usertags()->getMode() !== 'disabled') ? $this->driver->getTags(
              null === $list_id ? true : $list_id, // get tags for all lists if no single list is selected
              $user_id, 'tag'
             ) : array();
          ?>
          <? if (count($listTags) > 0): ?>
            <strong><?=$this->transEsc('Your Tags')?>:</strong>
            <? foreach ($listTags as $tag): ?>
              <a href="<?=$this->currentPath() . $results->getUrlQuery()->addFacet('tags', $tag->tag)?>"><?=$this->escapeHtml($tag->tag)?></a>
            <? endforeach; ?>
            <br/>
          <? endif; ?>
          <? $listNotes = $this->driver->getListNotes($list_id, $user_id); ?>
          <? if (count($listNotes) > 0): ?>
            <strong><?=$this->transEsc('Notes')?>:</strong>
            <? if (count($listNotes) > 1): ?><br/><? endif; ?>
            <? foreach ($listNotes as $note): ?>
              <?=$this->escapeHtml($note)?><br/>
            <? endforeach; ?>
          <? endif; ?>

          <? if (count($this->lists) > 0): ?>
              <strong><?=$this->transEsc('Saved in')?>:</strong>
              <? $i=0;foreach($this->lists as $current): ?>
                  <a href="<?=$this->url('userList', array('id' => $current->id))?>"><?=$this->escapeHtml($current->title)?></a><? if($i++ < count($this->lists)-1): ?>,<? endif; ?>
              <? endforeach; ?>
              <br/>
          <? endif; ?>

          <div class="callnumAndLocation ajax-availability hidden">
            <? if ($this->driver->supportsAjaxStatus()): ?>
              <strong><?=$this->transEsc('Located')?>:</strong>
              <span class="location ajax-availability hidden">
                <?=$this->transEsc('Loading')?>...
              </span>
              <div class="locationDetails"></div>
            <? else: ?>
              <? $summCallNo = $this->driver->getCallNumber(); if (!empty($summCallNo)): ?>
                <strong><?=$this->transEsc('Call Number')?>:</strong> <?=$this->escapeHtml($summCallNo)?>
              <? endif; ?>
            <? endif; ?>
          </div>

          <? /* We need to find out if we're supposed to display an OpenURL link ($openUrlActive),
                but even if we don't plan to display the link, we still want to get the $openUrl
                value for use in generating a COinS (Z3988) tag -- see bottom of file.
              */
            $openUrl = $this->openUrl($this->driver, 'results');
            $openUrlActive = $openUrl->isActive();
            // Account for replace_other_urls setting
            $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);

            if ($openUrlActive || !empty($urls)):
          ?>
            <? if ($openUrlActive): ?>
              <br/>
              <?=$openUrl->renderTemplate()?>
            <? endif;?>

            <? if (!is_array($urls)) { $urls = array(); }
              if(!$this->driver->isCollection()):
                foreach ($urls as $current): ?>
                  <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>" class="fulltext" target="new"><i class="fa fa-external-link" aria-hidden="true"></i> <?=($current['url'] == $current['desc']) ? $this->transEsc('Get full text') : $this->escapeHtml($current['desc'])?></a>
                <? endforeach; ?>
              <? endif; ?>
            <? endif; ?>

          <?=$this->record($this->driver)->getFormatList() ?>

          <? if (!$openUrlActive && empty($urls) && $this->driver->supportsAjaxStatus()): ?>
            <span class="status ajax-availability hidden"><?=$this->transEsc('Loading')?>...</span>
            <br/><br/>
          <? endif; ?>
          <?=$this->record($this->driver)->getPreviews()?>
        </div>

      <div class="result-actions hidden-print">
        <a href="<?=$this->url('myresearch-edit')?>?id=<?=urlencode($id)?>&amp;source=<?=urlencode($source)?><? if (!is_null($list_id)):?>&amp;list_id=<?=urlencode($list_id)?><? endif; ?>" class="edit tool btn btn-sm btn-default"><i class="fa fa-fw fa-edit" aria-hidden="true"></i> <?=$this->transEsc('Edit')?></a><br/>
        <? /* Use a different delete URL if we're removing from a specific list or the overall favorites: */
          $deleteUrl = null === $list_id
              ? $this->url('myresearch-favorites')
              : $this->url('userList', array('id' => $list_id));
          $deleteUrlGet = $deleteUrl . '?delete=' . urlencode($id) . '&amp;source=' . urlencode($source);

          $dLabel = 'delete-label-' . preg_replace('[\W]','-',$id);
        ?>
        
        <?=$this->driver->supportsCoinsOpenUrl()?'<span class="Z3988" title="'.$this->escapeHtmlAttr($this->driver->getCoinsOpenUrl()).'"></span>':''?>
      </div>
    <? if ($thumbnail && $thumbnailAlignment == 'right'): ?>
      <?=$thumbnail ?>
    <? endif; ?>
  </div>
</div>
